version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: BigData
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snowflake
    ports:
      - "6432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./исходные данные:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.50'
          memory: 1G
    restart: unless-stopped
    tty: true
    stdin_open: true